import 'package:usp_protocol_common/usp_protocol_common.dart';
import 'package:usp_device2_simulator/domain/repositories/i_device_repository.dart';

class UspMessageAdapter {
  final IDeviceRepository _repository;

  UspMessageAdapter(this._repository);

  /// Core processing entry point: Input Request DTO -> Output Response DTO
  Future<UspMessage> handleRequest(UspMessage requestDto) async {
    try {
      // Log the incoming request type
      print('\n🔵 [Adapter] Handling ${requestDto.runtimeType}...');

      return switch (requestDto) {
        UspGetRequest r => await _handleGet(r),
        UspSetRequest r => await _handleSet(r),
        UspAddRequest r => await _handleAdd(r),
        UspDeleteRequest r => await _handleDelete(r),
        UspGetSupportedDMRequest r => await _handleGetSupportedDM(r),
        UspOperateRequest r => await _handleOperate(r),
        UspGetInstancesRequest r => await _handleGetInstances(r),
        _ =>
          throw UspException(
            7004,
            "Unsupported Request: ${requestDto.runtimeType}",
          ),
      };
    } on UspException catch (e) {
      // Catch expected business exceptions (e.g., Path Not Found)
      print(
        '   ❌ [Adapter Error] USP Exception: ${e.errorCode} - ${e.message}',
      );
      return UspErrorResponse(e);
    } catch (e) {
      // Catch unexpected system errors
      print('   🔥 [Adapter Panic] System Error: $e');
      return UspErrorResponse(UspException(7000, "Internal Error: $e"));
    }
  }

  // --- Get Logic ---
  Future<UspGetResponse> _handleGet(UspGetRequest req) async {
    final results = <UspPath, UspValue>{};
    print('   🔍 [GET] Requesting ${req.paths.length} paths:');

    for (final path in req.paths) {
      try {
        final partial = await _repository.getParameterValue(path);

        if (partial.isNotEmpty) {
          partial.forEach((k, v) {
            print('      ✅ Found: ${k.fullPath} = "${v.value}"');
          });
          results.addAll(partial);
        } else {
          print('      ⚠️ Empty result for: ${path.fullPath}');
        }
      } on UspException catch (e) {
        print('      ⚠️ USP Error: ${path.fullPath} (${e.errorCode})');
      } catch (e) {
        print('      🔥 Critical Error: ${path.fullPath} ($e)');
        rethrow;
      }
    }
    return UspGetResponse(results);
  }

  // --- Set Logic ---
  Future<UspSetResponse> _handleSet(UspSetRequest req) async {
    final success = <UspPath>[];
    final failures = <UspPath, UspException>{};

    print('   ✏️ [SET] Attempting to update ${req.updates.length} items:');

    for (final entry in req.updates.entries) {
      final pathStr = entry.key.fullPath;
      final valStr = entry.value.value;

      try {
        await _repository.setParameterValue(entry.key, entry.value);
        success.add(entry.key);
        print('      ✅ Updated: $pathStr -> "$valStr"');
      } on UspException catch (e) {
        failures[entry.key] = e;
        print('      ❌ Failed: $pathStr (Error: ${e.errorCode})');

        if (!req.allowPartial) {
          print('      ⛔ Aborting Set due to allowPartial=false');
          break;
        }
      }
    }

    // If partial success is not allowed and there are failures, throw the first error
    if (!req.allowPartial && failures.isNotEmpty) {
      throw failures.values.first;
    }
    return UspSetResponse(successPaths: success, failurePaths: failures);
  }

  // --- Add Logic ---
  Future<UspAddResponse> _handleAdd(UspAddRequest req) async {
    final created = <UspCreatedObject>[];
    // Note: DTO should ideally support returning a list of errors for partial success scenarios

    print('   🌱 [ADD] Creating ${req.objects.length} objects:');

    for (final obj in req.objects) {
      try {
        // Call Repository to add object
        final newPath = await _repository.addObject(
          obj.parentPath,
          "Ignored", // Name is handled internally
          // instanceId: Automatically generated by Server
        );

        print('      ✅ Created Instance: ${newPath.fullPath}');

        // Handle initial parameter settings
        for (final paramEntry in obj.parameters.entries) {
          final paramPath = UspPath.parse(
            '${newPath.fullPath}.${paramEntry.key}',
          );
          await _repository.setParameterValue(paramPath, paramEntry.value);
          print(
            '         + Init Param: ${paramEntry.key} = ${paramEntry.value.value}',
          );
        }
        created.add(UspCreatedObject(newPath));
      } on UspException catch (e) {
        print('      ❌ Add Failed: ${obj.parentPath.fullPath} ($e)');
        if (!req.allowPartial) rethrow;
      }
    }
    return UspAddResponse(createdObjects: created);
  }

  // --- Delete Logic ---
  Future<UspDeleteResponse> _handleDelete(UspDeleteRequest req) async {
    final deleted = <UspPath>[];
    print('   🗑️ [DELETE] Removing ${req.objPaths.length} objects:');

    for (final path in req.objPaths) {
      try {
        await _repository.deleteObject(path);
        deleted.add(path);
        print('      ✅ Deleted: ${path.fullPath}');
      } on UspException catch (e) {
        print('      ❌ Delete Failed: ${path.fullPath} ($e)');
        if (!req.allowPartial) rethrow;
      }
    }
    return UspDeleteResponse(deletedPaths: deleted);
  }

  // --- GetSupportedDM Logic ---
  Future<UspGetSupportedDMResponse> _handleGetSupportedDM(UspGetSupportedDMRequest req) async {
    final results = <String, UspObjectDefinition>{};
    print('   ℹ️ [GET_SUPPORTED_DM] Requesting ${req.objPaths.length} paths:');

    for (final path in req.objPaths) {
      try {
        // The interface returns a Map (UspSupportedDMObject), which includes the node and its descendants
        final supportedObjMap = await _repository.getSupportedDM(path);
        
        // Use addAll to merge the entire definition into the results
        // This resolves the "Map cannot insert Value" type error and recursive data issues.
        results.addAll(supportedObjMap);
        
        print('      ✅ Found metadata for: ${path.fullPath} (${supportedObjMap.length} objects)');
      } on UspException catch (e) {
        print('      ⚠️ USP Error: ${path.fullPath} (${e.errorCode})');
      }
    }
    return UspGetSupportedDMResponse(results);
  }

  // --- Operate Logic ---
  Future<UspOperateResponse> _handleOperate(UspOperateRequest req) async {
    print('   ⚙️ [OPERATE] Executing: ${req.command.fullPath}');
    // inputArgs is Map<String, UspValue>
    if (req.inputArgs.isNotEmpty) {
      print('      Input Args: ${req.inputArgs}');
    }

    try {
      // Call Repository to execute the command
      // The return value should be Map<String, UspValue> (Output Args)
      // Or empty (if it's an asynchronous command that sends Notify later)
      final outputArgs = await _repository.operate(req.command, req.inputArgs);
      
      print('      ✅ Operation Successful (Sync Response)');
      return UspOperateResponse(outputArgs: outputArgs);
      
    } catch (e) {
      print('      ❌ Operation Failed: $e');
      rethrow; // 讓外層轉為 UspErrorResponse
    }
  }

  // --- GetInstances Logic ---
  Future<UspGetInstancesResponse> _handleGetInstances(UspGetInstancesRequest req) async {
    print('   📂 [GET_INSTANCES] Querying ${req.objPaths.length} paths (FirstLevel: ${req.firstLevelOnly})');
    
    final results = <String, List<UspInstanceResult>>{};

    for (final path in req.objPaths) {
      try {
        // Call Repository to query instances
        // The getInstances method needs to be added to IDeviceRepository
        final instances = await _repository.getInstances(path, req.firstLevelOnly);
        
        results[path.fullPath] = instances;
        print('      ✅ Found ${instances.length} instances for ${path.fullPath}');
        
      } on UspException catch (e) {
        print('      ⚠️ USP Error: ${path.fullPath} (${e.errorCode})');
      }
    }
    
    return UspGetInstancesResponse(results);
  }

}
